# config.yaml
robot:
  ip: "192.168.58.2"
  tool_id: 0
  user_frame_id: 0
  velocity: 20.0
  emergency_delay: 0.5

path_saver:
  captures_dir: cloud
  path_file: cloud/poses.json

vision:
  realsense_width: 640
  realsense_height: 480
  realsense_fps: 30

logging:
  log_dir: "./logs"
  level: "INFO"
  json: true

cloud:
  output_dir: clouds

charuco:
  squares_x: 5
  squares_y: 7
  square_length: 0.035
  marker_length: 0.026
  aruco_dict: 5X5_100
  calib_output_dir: calibration/results2
  xml_file: charuco_cam.xml
  txt_file: charuco_cam.txt
  images_dir: cloud

handeye:
  # images_dir: calibration/handeye_data
  images_dir: cloud
  calib_output_dir: calibration/results
  npz_file: handeye.npz
  txt_file: handeye.txt
  method: all

cloud_pipeline:
  data_dir: captures
  charuco_xml: calibration/results/charuco_cam.xml
  handeye_txt: calibration/results/handeye_PARK.txt
  poses_file: captures/poses.json
  depth_scale: 0.001
  roi_limits:
    x: [-0.3, -0.1]
    y: [-0.2, 0.2]
    z: [0.02, 0.1]

gpt:
  deepseek_api_key: "key"
  anthropic_api_key: "key"
  deepseek_url: https://api.deepseek.com/v1/chat/completions
  anthropic_url: https://api.anthropic.com/v1/messages
