[build-system]
requires = ["setuptools>=64", "wheel", "cython>=3.0"]
build-backend = "setuptools.build_meta"

[project]
name = "robo"
version = "0.1.0"
description = "Robotics Vision & Calibration Suite"
readme = "README.md"
requires-python = "~=3.11"
dependencies = [
    "numpy",
    "open3d==0.19.0",
    "opencv-contrib-python==4.11.0.86",
    "pyrealsense2==2.55.1.6486",
    "pynput",
    "python-json-logger",
    "pyyaml",
    "scipy",
    "tqdm",
]

[project.scripts]
poses-saver = "robot.workflows:main_record_poses"
path-runner = "robot.workflows:main_run_path"
charuco-calib = "calibration.workflows:main_charuco"
handeye-calib = "calibration.workflows:main_handeye"
get-intrinsics = "vision.tools:main_intrinsics"
depth-check = "vision.tools:main_depth"
pointcloud-capture = "vision.tools:main_capture"
pointcloud-transform = "vision.tools:main_transform"
pointcloud-view = "vision.tools:main_view"
vis-pointcloud = "vision.tools:main_pipeline"

[tool.setuptools.package-data]
robot = ["*.py", "*.pyx"]

[tool.setuptools.packages.find]
where = ["."]
include = ["robot*", "utils*", "vision*", "calibration*"]
