robot:
  ip: "192.168.58.2"
  tool_id: 0
  user_frame_id: 0
  velocity: 20.0
  emergency_delay: 0.5

vision:
  realsense_width: 640
  realsense_height: 480
  realsense_fps: 30

logging:
  level: "INFO"
  json: true

charuco:
  squares_x: 5
  squares_y: 7
  square_length: 0.033
  marker_length: 0.025
  aruco_dict: "4X4_100"
  min_corners: 4
  outlier_std: 2.0
  analyze_corners: false
  visualize: false

handeye:
  method: "all"
  min_corners: 4
  outlier_std: 2.0
  visualize: false

sample_selector:
  enabled: false
  min_samples: 5
  max_iterations: 5
  trans_thresh: 0.01
  rot_thresh_deg: 5.0
  visualize: false

validation:
  aruco_dict: "4X4_100"
  squares_x: 5
  squares_y: 7
  square_length: 0.033
  marker_length: 0.025
  pixel_threshold: 1.0

edge_drawer:
  camera:
    width: 640
    height: 480
    decimation: 2
    filter_sigma: 1.0
  robot:
    ip: "192.168.58.2"
    velocity: 20.0
  edge:
    hull_alpha: 0.03
    sample_resolution: 0.0001
    speed: 0.03
    transform_path: "handeye.yaml"
    force_limit: 2.0
  logging:
    level: "INFO"
