robot:
  ip: "192.168.58.2"
  tool_id: 0
  user_frame_id: 0
  velocity: 20.0
  emergency_delay: 0.5

vision:
  realsense_width: 640
  realsense_height: 480
  realsense_fps: 30

logging:
  level: "INFO"
  json: true

charuco:
  squares_x: 5
  squares_y: 8
  square_length: 0.035
  marker_length: 0.026
  aruco_dict: "5X5_100"
  min_corners: 4
  outlier_std: 2.0
  analyze_corners: false
  visualize: false

handeye:
  method: "all"
  min_corners: 4
  outlier_std: 2.0
  visualize: false

validation:
  aruco_dict: "5X5_100"
  squares_x: 5
  squares_y: 8
  square_length: 0.035
  marker_length: 0.026
  pixel_threshold: 1.0
  board_lt_base: [-0.165, -0.365, 0.0]
  board_rb_base: [-0.4, -0.53, 0.0]
