
camera:
  width: 640
  height: 480
  decimation: 2
  filter_sigma: 1.0
robot:
  ip: "192.168.58.2"
  velocity: 20.0
edge:
  hull_alpha: 0.03
  sample_resolution: 0.0001
  speed: 0.03
  transform_path: "handeye.yaml"
  force_limit: 2.0
logging:
  level: INFO
